name: Beta CI/CD Pipeline

on:
  push:
    branches: [beta]
  pull_request:
    branches: [beta]

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run linting
        run: npm run lint

      - name: Build application
        run: npm run build
        env:
          # Set environment variables for the build
          NEXTAUTH_URL: ${{ secrets.BETA_NEXTAUTH_URL }}
          NEXTAUTH_SECRET: ${{ secrets.BETA_NEXTAUTH_SECRET }}
          DATABASE_URL: ${{ secrets.BETA_DATABASE_URL }}

      - name: Deploy to Vercel (Preview)
        uses: vercel/actions@v4
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-args: "--prod" # This deploys to the preview environment linked to the beta branch
          working-directory: ./
        env:
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
